"""
ZivoPay PDF Generator — Dynamic Layout
- Company info, logo, and branding pulled from invoice data
- Supports dynamic currency, tax, invoice number, and dates
- Blurred centred watermark + page-footer canvas callback + WhatsApp QR code
"""

import os
import uuid
from datetime import datetime

from reportlab.lib           import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles    import ParagraphStyle
from reportlab.lib.units     import mm
from reportlab.lib.enums     import TA_RIGHT, TA_CENTER, TA_LEFT
from reportlab.platypus      import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, Image
)

# ── Paths ──────────────────────────────────────────────────────────────────────
_HERE      = os.path.dirname(os.path.abspath(__file__))
_APP_DIR   = os.path.dirname(_HERE)
BASE_DIR   = os.path.dirname(_APP_DIR)
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
OUTPUT_DIR = os.path.join(BASE_DIR, "generated")

# ── Brand colours ──────────────────────────────────────────────────────────────
BRAND_PRIMARY  = colors.HexColor("#1E3A6E")
BRAND_LIGHT_BG = colors.HexColor("#EEF4FB")
BRAND_LINE     = colors.HexColor("#CBD8E8")
BRAND_GREY     = colors.HexColor("#6B7280")
BRAND_DARK     = colors.HexColor("#0D1B2A")
WHITE          = colors.white

# ── Currency symbol map ────────────────────────────────────────────────────────
CURRENCY_SYMBOLS = {
    "USD": "$", "ZWL": "ZWL ", "ZiG": "ZiG ",
    "ZAR": "R", "GBP": "£",   "EUR": "€",
}

# ── Company defaults ───────────────────────────────────────────────────────────
DEFAULT_COMPANY_NAME    = "Zivopay Digital Services Pvt Ltd"
DEFAULT_COMPANY_EMAIL   = "wekwamarufu@gmail.com"
DEFAULT_COMPANY_WEBSITE = "admin.zivopay.online"

DEFAULT_BANKING = (
    "Bank: National Building Society (NBS)\n"
    "Account Name: Freedom Installations Pvt Ltd\n"
    "USD Account No: 123456789\n"
    "ZiG Account No: 321654654\n"
    "Vendor No: 2582589\n"
    "Branch Code: XVCGF7845"
)

WA_QR_URL = "https://wa.me/263783739998"

# ── Cached file paths ──────────────────────────────────────────────────────────
_WM_BLURRED = os.path.join(OUTPUT_DIR, "_wm_blurred.png")
_QR_WA_PNG  = os.path.join(OUTPUT_DIR, "_qr_wa.png")

# ── Per-build state for canvas callbacks ───────────────────────────────────────
_page_state: dict = {}


# ── Asset helpers ──────────────────────────────────────────────────────────────

def _default_logo_path():
    for name in ("logo_transparent.png", "logo.png"):
        p = os.path.join(ASSETS_DIR, name)
        if os.path.exists(p):
            return p
    return None


def _watermark_path():
    p = os.path.join(ASSETS_DIR, "logo_watermark.png")
    return p if os.path.exists(p) else None


def _get_blurred_watermark() -> str | None:
    """Blur + soften the watermark PNG using Pillow and cache it."""
    wm = _watermark_path()
    if not wm:
        return None
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    try:
        from PIL import Image as PILImage, ImageFilter
        img = PILImage.open(wm).convert("RGBA")
        r, g, b, a = img.split()
        # 18% opacity — subtle background, not distracting
        a = a.point(lambda px: int(px * 0.30))
        img.putalpha(a)
        img = img.filter(ImageFilter.GaussianBlur(radius=3))
        img.save(_WM_BLURRED, "PNG")
        return _WM_BLURRED
    except Exception as e:
        print(f"[PDF] Watermark blur error: {e}")
        return wm   # fallback to original


def _get_qr_png() -> str | None:
    """Return the pre-generated WhatsApp QR code PNG, or try to generate it."""
    # Use cached file if it already exists (generated by setup or previous run)
    if os.path.exists(_QR_WA_PNG):
        return _QR_WA_PNG
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    try:
        import qrcode as _qrcode
        qr = _qrcode.QRCode(
            version=1,
            error_correction=_qrcode.constants.ERROR_CORRECT_M,
            box_size=8, border=2,
        )
        qr.add_data(WA_QR_URL)
        qr.make(fit=True)
        img = qr.make_image(fill_color="#1E3A6E", back_color="white")
        img.save(_QR_WA_PNG)
        return _QR_WA_PNG
    except Exception as e:
        print(f"[PDF] QR code error: {e}")
        return None


def _parse_date(value) -> datetime:
    if not value:
        return datetime.now()
    try:
        return datetime.fromtimestamp(int(value))
    except (ValueError, TypeError):
        pass
    try:
        return datetime.strptime(str(value), "%Y-%m-%d")
    except (ValueError, TypeError):
        pass
    return datetime.now()


# ── Styles ─────────────────────────────────────────────────────────────────────

def _styles():
    return {
        "company_name": ParagraphStyle("cn", fontSize=10, fontName="Helvetica-Bold",
            textColor=BRAND_PRIMARY, alignment=TA_CENTER, leading=13),
        "company_sub": ParagraphStyle("cs", fontSize=7.5, fontName="Helvetica",
            textColor=BRAND_GREY, alignment=TA_CENTER, leading=11),
        "doc_heading": ParagraphStyle("dh", fontSize=28, fontName="Helvetica-Bold",
            textColor=BRAND_PRIMARY, alignment=TA_RIGHT, leading=32, spaceAfter=16),
        "meta_label": ParagraphStyle("ml", fontSize=8, fontName="Helvetica-Bold",
            textColor=BRAND_GREY, alignment=TA_RIGHT, leading=14),
        "meta_value": ParagraphStyle("mv", fontSize=8.5, fontName="Helvetica",
            textColor=BRAND_DARK, alignment=TA_LEFT, leading=14),
        "bill_label": ParagraphStyle("bl", fontSize=7.5, fontName="Helvetica-Bold",
            textColor=WHITE),
        "client_detail": ParagraphStyle("cd", fontSize=9, fontName="Helvetica",
            textColor=BRAND_DARK, leading=13),
        "th": ParagraphStyle("th", fontSize=8.5, fontName="Helvetica-Bold",
            textColor=WHITE),
        "td": ParagraphStyle("td", fontSize=8.5, fontName="Helvetica",
            textColor=BRAND_DARK, leading=12),
        "td_r": ParagraphStyle("tdr", fontSize=8.5, fontName="Helvetica",
            textColor=BRAND_DARK, alignment=TA_RIGHT, leading=12),
        "total_lbl": ParagraphStyle("tl", fontSize=9, fontName="Helvetica",
            textColor=BRAND_GREY, alignment=TA_RIGHT),
        "total_val": ParagraphStyle("tv", fontSize=9, fontName="Helvetica",
            textColor=BRAND_DARK, alignment=TA_RIGHT),
        "grand_lbl": ParagraphStyle("gl", fontSize=11, fontName="Helvetica-Bold",
            textColor=WHITE, alignment=TA_RIGHT),
        "grand_val": ParagraphStyle("gv", fontSize=11, fontName="Helvetica-Bold",
            textColor=WHITE, alignment=TA_RIGHT),
        "sec_title": ParagraphStyle("st", fontSize=8, fontName="Helvetica-Bold",
            textColor=BRAND_PRIMARY, spaceAfter=3, leading=10, alignment=TA_LEFT),
        "body": ParagraphStyle("bd", fontSize=8.5, fontName="Helvetica",
            textColor=BRAND_DARK, leading=13, alignment=TA_LEFT),
        "qr_label": ParagraphStyle("ql", fontSize=7, fontName="Helvetica",
            textColor=BRAND_GREY, alignment=TA_CENTER, leading=10),
    }


# ── Canvas callbacks (watermark + page footer) ─────────────────────────────────

def _draw_page_elements(c, doc):
    """Draws the blurred watermark and a fixed footer on every page."""
    pw, ph = A4

    # ── Watermark ─────────────────────────────────────────────────────────────
    wm = _get_blurred_watermark()
    if wm and os.path.exists(wm):
        sz = 150 * mm
        x  = (pw - sz) / 2
        y  = (ph - sz) / 2
        c.saveState()
        c.drawImage(wm, x, y, width=sz, height=sz, mask="auto")
        c.restoreState()

    # ── Footer (always at bottom of page) ─────────────────────────────────────
    margin   = 14 * mm
    footer_y = 9 * mm      # distance from bottom edge

    c.saveState()

    # Thin separator line
    c.setStrokeColor(BRAND_LINE)
    c.setLineWidth(0.5)
    c.line(margin, footer_y + 5 * mm, pw - margin, footer_y + 5 * mm)

    # Footer text — company · email · website
    c.setFont("Helvetica", 7)
    c.setFillColor(BRAND_GREY)
    name    = _page_state.get("company_name",    DEFAULT_COMPANY_NAME)
    email   = _page_state.get("company_email",   DEFAULT_COMPANY_EMAIL)
    website = _page_state.get("company_website", DEFAULT_COMPANY_WEBSITE)
    line1   = f"{name}  •  {email}  •  {website}"
    c.drawCentredString(pw / 2, footer_y + 2 * mm, line1)

    c.setFont("Helvetica-Oblique", 7)
    c.drawCentredString(pw / 2, footer_y - 1 * mm, "Thank you for your business!")

    c.restoreState()


# ── Main generator ─────────────────────────────────────────────────────────────

def generate_pdf(data: dict) -> str:
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # ── Extract data ──────────────────────────────────────────────────────────
    doc_type = data.get("doc_type", "Invoice")
    currency = data.get("currency", "USD")
    sym      = CURRENCY_SYMBOLS.get(currency, currency + " ")

    company_name    = data.get("company_name")    or DEFAULT_COMPANY_NAME
    company_email   = data.get("company_email")   or DEFAULT_COMPANY_EMAIL
    company_phone   = data.get("company_phone")   or ""
    company_website = data.get("company_website") or DEFAULT_COMPANY_WEBSITE

    client_name    = data.get("client_name",    "Client")
    client_email   = data.get("client_email",   "")
    client_phone   = data.get("client_phone",   "")
    client_company = data.get("client_company", "")
    client_address = data.get("client_address", "")

    items      = data.get("items", [])
    subtotal   = round(sum(i["total"] for i in items), 2)
    tax_rate   = float(data.get("tax_rate") or 0)
    tax_amount = round(subtotal * tax_rate / 100, 2)
    total_due  = round(subtotal + tax_amount, 2)
    tax_number = data.get("tax_number", "")

    payment_terms   = data.get("payment_terms", "")
    po_number       = data.get("po_number", "")
    notes           = data.get("notes", "").strip()
    banking_details = (data.get("banking_details") or DEFAULT_BANKING).strip()
    lead_time       = data.get("lead_time", "")

    # ── Doc number & dates ────────────────────────────────────────────────────
    prefix  = "QUO" if doc_type == "Quotation" else "INV"
    doc_num = (data.get("invoice_number") or
               f"{prefix}-{datetime.now().strftime('%Y%m%d')}-{str(uuid.uuid4())[:4].upper()}")
    invoice_date = _parse_date(data.get("invoice_date"))
    due_date     = _parse_date(data.get("due_date")) if data.get("due_date") else None
    date_fmt     = "%d %B %Y"

    logo_p = data.get("company_logo_path") or _default_logo_path()

    safe_client = client_name.replace(" ", "_").replace("/", "-")
    filepath    = os.path.join(OUTPUT_DIR, f"{doc_num}_{safe_client}.pdf")

    # Store footer info for the canvas callback
    _page_state.update({
        "company_name":    company_name,
        "company_email":   company_email,
        "company_website": company_website,
    })

    s = _styles()
    W = A4[0] - 28 * mm   # usable width ≈ 182 mm
    story = []

    # ── HEADER ────────────────────────────────────────────────────────────────
    left = []
    if logo_p:
        logo_img  = Image(logo_p, width=44 * mm, height=44 * mm)
        logo_wrap = Table([[logo_img]], colWidths=[W * 0.46])
        logo_wrap.setStyle(TableStyle([
            ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
            ("LEFTPADDING",   (0, 0), (-1, -1), 0),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
            ("TOPPADDING",    (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        left.append(logo_wrap)

    left.append(Paragraph(company_name, s["company_name"]))
    if company_phone:
        left.append(Paragraph(company_phone, s["company_sub"]))
    contact_line = "  |  ".join(filter(None, [company_email, company_website]))
    if contact_line:
        left.append(Paragraph(contact_line, s["company_sub"]))

    # Right: heading + meta table
    meta_rows = [
        [Paragraph("Date:",           s["meta_label"]), Paragraph(invoice_date.strftime(date_fmt), s["meta_value"])],
        [Paragraph(f"{doc_type} No:", s["meta_label"]), Paragraph(doc_num,                         s["meta_value"])],
    ]
    if due_date:
        meta_rows.append([Paragraph("Due Date:",   s["meta_label"]), Paragraph(due_date.strftime(date_fmt), s["meta_value"])])
    if payment_terms:
        meta_rows.append([Paragraph("Terms:",      s["meta_label"]), Paragraph(payment_terms,               s["meta_value"])])
    if lead_time:
        meta_rows.append([Paragraph("Lead Time:",  s["meta_label"]), Paragraph(lead_time,                   s["meta_value"])])
    if po_number:
        meta_rows.append([Paragraph("PO Number:",  s["meta_label"]), Paragraph(po_number,                   s["meta_value"])])
    if tax_number:
        meta_rows.append([Paragraph("Tax/VAT No:", s["meta_label"]), Paragraph(tax_number,                  s["meta_value"])])

    meta_tbl = Table(meta_rows, colWidths=[24 * mm, 46 * mm])
    meta_tbl.setStyle(TableStyle([
        ("ALIGN",         (0, 0), (0, -1), "RIGHT"),
        ("ALIGN",         (1, 0), (1, -1), "LEFT"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("LEFTPADDING",   (0, 0), (-1, -1), 0),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
    ]))

    right = [Paragraph(doc_type.upper(), s["doc_heading"]), meta_tbl]
    hdr   = Table([[left, right]], colWidths=[W * 0.46, W * 0.54])
    hdr.setStyle(TableStyle([
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING",   (0, 0), (-1, -1), 0),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
        ("TOPPADDING",    (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(hdr)
    story.append(Spacer(1, 5))
    story.append(HRFlowable(width="100%", thickness=1.2, color=BRAND_PRIMARY, spaceAfter=7))

    # ── BILL TO ───────────────────────────────────────────────────────────────
    bt_lines = f"<b>{client_name}</b>"
    if client_company: bt_lines += f"<br/>{client_company}"
    if client_address: bt_lines += f"<br/>{client_address}"
    if client_email:   bt_lines += f"<br/>{client_email}"
    if client_phone:   bt_lines += f"<br/>{client_phone}"

    bill_hdr = Table([[Paragraph("BILL TO", s["bill_label"])]], colWidths=[W])
    bill_hdr.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), BRAND_PRIMARY),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
    ]))
    bill_body = Table([[Paragraph(bt_lines, s["client_detail"])]], colWidths=[W])
    bill_body.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), BRAND_LIGHT_BG),
        ("TOPPADDING",    (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
    ]))
    story.append(bill_hdr)
    story.append(bill_body)
    story.append(Spacer(1, 8))

    # ── LINE ITEMS ────────────────────────────────────────────────────────────
    cw   = [W * 0.50, W * 0.12, W * 0.19, W * 0.19]
    rows = [[
        Paragraph("DESCRIPTION",              s["th"]),
        Paragraph("QTY",                      s["th"]),
        Paragraph(f"UNIT PRICE ({currency})", s["th"]),
        Paragraph(f"TOTAL ({currency})",      s["th"]),
    ]]
    for item in items:
        qty_str = str(int(item["qty"])) if item["qty"] == int(item["qty"]) else str(item["qty"])
        rows.append([
            Paragraph(item["description"],              s["td"]),
            Paragraph(qty_str,                          s["td"]),
            Paragraph(f"{sym}{item['unit_price']:.2f}", s["td_r"]),
            Paragraph(f"{sym}{item['total']:.2f}",      s["td_r"]),
        ])

    itbl = Table(rows, colWidths=cw, repeatRows=1)
    itbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0),  BRAND_PRIMARY),
        ("TOPPADDING",    (0, 0), (-1, 0),  8),
        ("BOTTOMPADDING", (0, 0), (-1, 0),  8),
        ("LEFTPADDING",   (0, 0), (-1, 0),  8),
        ("RIGHTPADDING",  (0, 0), (-1, 0),  8),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, BRAND_LIGHT_BG]),
        ("TOPPADDING",    (0, 1), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 7),
        ("LEFTPADDING",   (0, 1), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 1), (-1, -1), 8),
        ("ALIGN",         (1, 0), (-1, -1), "RIGHT"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("LINEBELOW",     (0, 0), (-1, -1), 0.3, BRAND_LINE),
    ]))
    story.append(itbl)
    story.append(Spacer(1, 4))

    # ── TOTALS ────────────────────────────────────────────────────────────────
    tw    = W * 0.43
    col_w = [tw * 0.58, tw * 0.42]
    totals_rows = [
        [Paragraph(f"Subtotal ({currency})", s["total_lbl"]),
         Paragraph(f"{sym}{subtotal:.2f}",   s["total_val"])],
    ]
    if tax_rate:
        totals_rows.append([
            Paragraph(f"Tax ({tax_rate:.0f}%)", s["total_lbl"]),
            Paragraph(f"{sym}{tax_amount:.2f}", s["total_val"]),
        ])

    sub_tbl = Table(totals_rows, colWidths=col_w)
    sub_tbl.setStyle(TableStyle([
        ("ALIGN",         (0, 0), (-1, -1), "RIGHT"),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("LINEBELOW",     (0, -1), (-1, -1), 0.5, BRAND_LINE),
    ]))

    grand_tbl = Table(
        [[Paragraph(f"TOTAL DUE ({currency})", s["grand_lbl"]),
          Paragraph(f"{sym}{total_due:.2f}",   s["grand_val"])]],
        colWidths=col_w,
    )
    grand_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), BRAND_PRIMARY),
        ("ALIGN",         (0, 0), (-1, -1), "RIGHT"),
        ("TOPPADDING",    (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
    ]))

    totals_block = Table([[sub_tbl], [grand_tbl]], colWidths=[tw])
    totals_block.setStyle(TableStyle([
        ("LEFTPADDING",   (0, 0), (-1, -1), 0),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
        ("TOPPADDING",    (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    totals_wrap = Table([["", totals_block]], colWidths=[W - tw, tw])
    totals_wrap.setStyle(TableStyle([
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING",   (0, 0), (-1, -1), 0),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
        ("TOPPADDING",    (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(totals_wrap)
    story.append(Spacer(1, 12))

    # ── SEPARATOR ─────────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=0.5, color=BRAND_LINE, spaceAfter=10))

    # ── NOTES (directly in story, no table wrapper) ───────────────────────────
    if notes:
        story.append(Paragraph("NOTES &amp; INSTRUCTIONS", s["sec_title"]))
        for line in notes.split("\n"):
            if line.strip():
                story.append(Paragraph(line.strip(), s["body"]))
        story.append(Spacer(1, 8))

    # ── BANKING DETAILS + QR (banking hard-left, QR floated right) ───────────
    # Build banking paragraphs
    bank_cell = [Paragraph("BANKING DETAILS", s["sec_title"])]
    for line in banking_details.split("\n"):
        if line.strip():
            bank_cell.append(Paragraph(line.strip(), s["body"]))

    # Build QR cell
    qr_cell = [Spacer(1, 1)]
    qr_path = _get_qr_png()
    if qr_path and os.path.exists(qr_path):
        qr_cell = [
            Image(qr_path, width=56 * mm, height=56 * mm),
        ]

    bq = Table(
        [[bank_cell, qr_cell]],
        colWidths=[W * 0.62, W * 0.38],
    )
    bq.setStyle(TableStyle([
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("ALIGN",         (0, 0), (0,  0),  "LEFT"),
        ("ALIGN",         (1, 0), (1,  0),  "CENTER"),
        # Banking column — ZERO left padding, starts at page margin
        ("LEFTPADDING",   (0, 0), (0,  0),  0),
        ("RIGHTPADDING",  (0, 0), (0,  0),  6),
        ("TOPPADDING",    (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("LEFTPADDING",   (1, 0), (1,  0),  6),
        ("RIGHTPADDING",  (1, 0), (1,  0),  0),
    ]))
    story.append(bq)

    # ── BUILD ─────────────────────────────────────────────────────────────────
    doc_obj = SimpleDocTemplate(
        filepath, pagesize=A4,
        leftMargin=14 * mm, rightMargin=14 * mm,
        topMargin=14 * mm,  bottomMargin=22 * mm,
    )
    # NOTE: onFirstPage/onLaterPages MUST go into build(), not the constructor
    doc_obj.build(story, onFirstPage=_draw_page_elements, onLaterPages=_draw_page_elements)
    print(f"[PDF] Generated: {filepath}")
    return filepath
